name: Build Base Image for 'docgen'

env:
  IMAGE_NAME: s2obcn/jdk-11_openj9-wkhtmltopdf-ubi
  MODULE_NAME: 'docgen'

on:
  pull_request:
    paths:
      - "docgen/**"
  push:
    branches:
      - 'main'
    paths:
      - "docgen/**"

jobs:
  buildImage:
    name: docgen - Build Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta - ubi8
        id: meta-ubi8
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}-ubi8
          tags: |
            type=sha
            type=raw,value=latest
      -
        name: Docker meta - centos7
        id: meta-centos7
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}-centos7
          tags: |
            type=sha
            type=raw,value=latest
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ubi
        uses: docker/build-push-action@v2
        with:
          context: ${{env.MODULE_NAME}}
          file: ${{env.MODULE_NAME}}/Dockerfile.ubi8
          build-args: ${{env.BUILD_ARGS}}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ubi8.outputs.tags }}
          labels: ${{ steps.meta-ubi8.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
      -
        name: Build and push centos7
        uses: docker/build-push-action@v2
        with:
          context: ${{env.MODULE_NAME}}
          file: ${{env.MODULE_NAME}}/Dockerfile.centos7
          build-args: ${{env.BUILD_ARGS}}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-centos7.outputs.tags }}
          labels: ${{ steps.meta-centos7.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha