name: Build Base Image for 'golang'

on:
  pull_request:
    paths:
      - "golang/**"
  push:
    branches:
      - 'main'
    paths:
      - "golang/**"

jobs:
  golang_module:
    uses: ./.github/workflows/publish-two-docker.yml
    secrets:
      dockeHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      module: 'golang'
      imageName: 's2obcn/golang-test'
      buildArgs: |
        goDistributionUrl=https://golang.org/dl/go1.14.2.linux-amd64.tar.gz