name: Build Base Image for 'golang'

env:
  IMAGE_NAME: s2obcn/golang-test
  MODULE_NAME: 'golang'
  BUILD_ARGS: |
    goDistributionUrl=https://golang.org/dl/go1.14.2.linux-amd64.tar.gz

on:
  pull_request:
    paths:
      - "golang/**"
  push:
    branches:
      - 'main'
    paths:
      - "golang/**"

jobs:
  buildImage:
    name: golang - Build Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}
          tags: |
            type=edge
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ubi
        uses: docker/build-push-action@v2
        with:
          context: ${{env.MODULE_NAME}}
          file: ${{env.MODULE_NAME}}/Dockerfile.ubi8
          build-args: ${{env.BUILD_ARGS}}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }},  ${{env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
      -
        name: Build and push centos7
        uses: docker/build-push-action@v2
        with:
          context: ${{env.MODULE_NAME}}
          file: ${{env.MODULE_NAME}}/Dockerfile.centos7
          build-args: ${{env.BUILD_ARGS}}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }},  ${{env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
