name: Build Base Image for 'maven'

on:
  pull_request:
    paths:
      - "maven/**"
  push:
    branches:
      - 'main'
    paths:
      - "maven/**"

jobs:
  maven_module:
    uses: ./.github/workflows/publish-two-docker.yml
    secrets:
      dockeHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      module: 'maven'
      imageName: 's2obcn/maven-test'
      buildArgs: |
        nexusUrl=https://nexus.example.com
        nexusUsername=developer
        nexusPassword=s3cr3t
    