name: Build Base Image for 'nodejs16'

on:
  pull_request:
    paths:
      - "nodejs16/**"
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-nodejs16.*"

jobs:
  nodejs16_module:
    uses: ./.github/workflows/publish-two-docker-images.yml
    secrets:
      dockeHubUser: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      module: 'nodejs16'
      imageName: 's2obcn/nodejs16-test'
      buildArgs: |
        nexusUrl=https://nexus.example.com
        nexusAuth=developer:s3cr3t
    